---
title: "Transform your Data"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    resize_reload: false
    css: "www/tyd.css"
    includes:
      after_body: "www/footer.html"   
runtime: shiny_prerendered
---

```{r, echo=FALSE}
shiny::addResourcePath("shinyjs", system.file("srcjs", package = "shinyjs"))
```

```{r, context="server"}
shinyjs::useShinyjs(html = TRUE)
```

```{=html}
<script src="shinyjs/inject.js"></script>
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
shinyFeedback::useShinyFeedback()
shinyjs::useShinyjs(rmd = TRUE)
library(magrittr)
source("R/utils.R")
```

```{r TODO}
# grouped data option only available for 3 or more columns - add message
# column output - the grouping variable should default to the column with the fewest unique values
# column output for coyotes - variables not displaying

```

### Original data

```{r}
DT::dataTableOutput(outputId = "original_data")
```

------------------------------------------------------------------------

::: upload-text
Upload dataset

```{r}
fileInput(inputId = "input_file", label = NULL)
```

OR

```{r}
actionButton(inputId = "example_data", label = "Use example data")
```
<br>
<br>
Datasets must have column headings

:::

### Grouped output

```{r}
uiOutput("grouped_output")
```

------------------------------------------------------------------------

```{r}
selectInput(inputId = "grouping_var", label = "Choose grouping variable", choices = "")
selectInput(inputId = "row_names", label = "Choose variable for row names", choices = "")
selectInput(inputId = "data_values", label = "Choose data values", choices = "")
br()
(downloadButton(outputId = "download_grouped", label = "download data"))
br()
(actionButton(inputId = "copy_grouped", label = "copy data to clipboard"))
```

### Column output

```{r}
uiOutput("column_output")
#DT::dataTableOutput(outputId = "column_table")
```

------------------------------------------------------------------------

```{r}
selectInput(inputId = "column_grouping_var", label = "Choose grouping variable", choices = "")
selectInput(inputId = "column_data_values", label = "Choose data values", choices = "")
br()
(downloadButton(outputId = "download_column", label = "download data"))
br()
actionButton(inputId = "copy_column", label = "copy data to clipboard")
```

### Transpose

```{r}
uiOutput("transposed_output")
```

------------------------------------------------------------------------

```{r}
br()
(downloadButton(outputId = "download_transposed", label = "download data"))
p(class="load_ds_msg", id="download_transposed", "This format will only download as a file if the dataset has (unique) row and column names.")
br()
actionButton(inputId = "copy_transposed", label = "copy data to clipboard")
```

### Contingency table

```{r}
uiOutput("contingency_output")
```

------------------------------------------------------------------------

```{r}
selectInput(inputId = "contingency_varA", label = "Choose variable A", choices = "")
selectInput(inputId = "contingency_varB", label = "Choose variable B", choices = "")
br()
(downloadButton(outputId = "download_contingency", label = "download data"))
br()
actionButton(inputId = "copy_contingency", label = "copy data to clipboard")
```

### Bizarre (XY)

```{r}
uiOutput("XY_output")
```

------------------------------------------------------------------------

```{r}
selectInput(inputId = "XY_id", label = "Choose ID column", choices = "")
selectInput(inputId = "XY_varX", label = "Choose X variable", choices = "")
selectInput(inputId = "XY_Yval", label = "Choose Y values", choices = "")
selectInput(inputId = "XY_Ygroup", label = "Choose Y grouping", choices = "")
br()
(downloadButton(outputId = "download_XY", label = "download data"))
br()
actionButton(inputId = "copy_XY", label = "copy data to clipboard")
```

```{r XY_processing, context="server"}
my_XY_dataset <- reactive({
  req(dataset())
  # if(input$XY_id == "add_ID") {
  #   my_dataset <- dplyr::mutate(dataset(), ID = dplyr::row_number())
  # } else {
  #   my_dataset <- dplyr::mutate(dataset(), ID = input$XY_id)
  # }
  my_dataset <- dataset()
  
  my_dataset |>
    dplyr::select(input$XY_id, input$XY_varX, input$XY_Yval, input$XY_Ygroup) |>
    tidyr::pivot_wider(names_prefix = paste0(input$XY_Yval, "_"), values_from=input$XY_Yval, names_from = input$XY_Ygroup)
})  
```

```{r XY_ui, context="server"}
output$XY_output <- renderUI({
  #browser()
    #browser()
  tabsetPanel(
    tabPanel("Data",  
             create_table_UI("XY_table", isTruthy(dataset()), min_no_col=3, actual_no_col=no_of_cols())),
    tabPanel("Example", 
             br(),
             p("An example of this format"),
             show_data_table(readRDS("data/XY_eg.rds"))
             )
  )
 # create_table_UI("XY_table", isTruthy(dataset()), min_no_col=3, actual_no_col=no_of_cols())
})

output$XY_table <- DT::renderDataTable({
  req(my_XY_dataset())
  show_data_table(my_XY_dataset())
})
```

```{r download_XY, context="server"}
output$download_XY <- create_download_handler(my_XY_dataset(), "XY_dataset")

observeEvent(input$copy_XY, {
  clipr::write_clip(my_XY_dataset(), allow_non_interactive=TRUE)
})
```

```{r functions, context="server"}
duplicate_warning <- function(a, b){
  shinyFeedback::feedbackDanger(
    inputId = a,
    show = input[[a]] == input[[b]],
    text = "No duplications allowed"
  )
  shinyFeedback::feedbackDanger(
    inputId = b,
    show = input[[a]] == input[[b]],
    text = "No duplications allowed"
  )
}

hide_download_btns()
shinyjs::hide("download_transposed")
```

```{r import_data, context="server"}
dataset <- reactiveVal()
no_of_cols <- reactiveVal()
data_path <- reactive(input$input_file$datapath)

not_all_na <- function(x) {!all(is.na(x))}

read_dataset <- function(filepath){
  dataset <- switch(tools::file_ext(filepath), 
    tsv = ,
    dat = ,
    txt = readr::read_tsv(filepath),
    csv = readr::read_csv(filepath),
    xls = ,
    xlsx = readxl::read_excel(filepath),
    stop("Unknown file extension on data file")
  )
  # remove any rows or columns that are all NA
  dataset %>%
    dplyr::filter(dplyr::if_any(tidyselect::everything(), ~ !is.na(.))) %>%
    dplyr::select_if(not_all_na)
}

observeEvent(data_path(), {
  
  imported_data <- read_dataset(data_path())
  # some nice thorough checks here...
  dataset(imported_data)
})

observeEvent(input$example_data, {
  imported_data <- readRDS("data/test_data.rds")
  dataset(imported_data)
})

observeEvent(dataset(), {
  column_names <- colnames(dataset())
  
  no_of_cols(length(column_names))
  
  data_selection <- dplyr::if_else(
    #length(column_names) > 2,
    no_of_cols() > 2, 
    column_names[3], 
    column_names[2]
  )
  
  print(dataset())  
  
  unique_values <- dplyr::summarise(dataset(), dplyr::across(dplyr::everything(), dplyr::n_distinct))
  
  print(unique_values)  
  s1 <- names(which.min(unique_values))
  s2 <- names(which.max(unique_values))
  print(s1)
  
  updateSelectInput(inputId="column_grouping_var", choices=column_names, selected = s1)
  updateSelectInput(inputId="column_data_values", choices=column_names, selected = s2)
  #updateSelectInput(inputId="column_data_values", choices=column_names, selected = data_selection)
  
  show_download_btns()
  
  updateSelectInput(inputId="grouping_var", choices=column_names)
  updateSelectInput(inputId="row_names", choices=column_names, selected = column_names[2])
  updateSelectInput(inputId="data_values", choices=column_names, selected = data_selection)

  updateSelectInput(inputId = "XY_id", label = "Choose ID column", choices = column_names)
  updateSelectInput(inputId = "XY_varX", label = "Choose X variable", choices = column_names)
  updateSelectInput(inputId = "XY_Yval", label = "Choose Y values", choices = column_names, selected=column_names[2])
  updateSelectInput(inputId = "XY_Ygroup", label = "Choose Y grouping", choices = column_names, selected=data_selection)

  updateSelectInput(inputId="contingency_varA", choices=column_names)
  updateSelectInput(inputId="contingency_varB", choices=column_names, selected = column_names[2])
  
  if(! is.data.frame(my_transposed_dataset())){
    shinyjs::hide("download_transposed")
    shinyjs::show("download_transposed_msg") 
  }
  
  if(length(column_names) < 3){
    shinyjs::hide("download_grouped")
    shinyjs::hide("download_XY")
  }

})

output$original_data <- DT::renderDataTable({
  req(dataset())
  DT::datatable(dataset(), rownames = FALSE, options = dt_options) %>% 
    DT::formatStyle(0, target = 'row', `font-size` = '90%', lineHeight = '80%')
})
```

```{r grouped_processing, context="server"}
observe({
  req(dataset())
  shinyFeedback::feedbackDanger(
    inputId = "grouping_var",
    show = input$grouping_var %in% c(input$row_names, input$data_values),
    text = "No duplications allowed"
  )
  shinyFeedback::feedbackDanger(
    inputId = "row_names",
    show = input$row_names %in% c(input$data_values, input$grouping_var),
    text = "No duplications allowed"
  )
  shinyFeedback::feedbackDanger(
    inputId = "data_values",
    show = input$data_values %in% c(input$row_names, input$grouping_var),
    text = "No duplications allowed"
  )
  if(anyDuplicated(c(input$row_names, input$data_values, input$grouping_var)) == 0){
    shinyFeedback::hideFeedback("grouping_var")
    shinyFeedback::hideFeedback("row_names")
    shinyFeedback::hideFeedback("data_values")
  } else {
    if(! input$grouping_var %in% c(input$row_names, input$data_values)) {
      shinyFeedback::hideFeedback("grouping_var")
    }
    if(! input$row_names %in% c(input$data_values, input$grouping_var)) {
      shinyFeedback::hideFeedback("row_names")
    }
    if(! input$data_values %in% c(input$row_names, input$grouping_var)) {
       shinyFeedback::hideFeedback("data_values")
    }
  }
})

# check if there's a unique identifier
my_grouped_dataset <- reactive({
  req(dataset())
  req(anyDuplicated(c(input$row_names, input$data_values, input$grouping_var)) == 0)
  create_grouped_output(dataset(), input$row_names, input$data_values, input$grouping_var)
})
```

```{r grouped_ui, context="server"}
output$grouped_output <- renderUI(create_table_UI("grouped_table", isTruthy(dataset()), min_no_col=3, actual_no_col=no_of_cols()))

output$grouped_table <- DT::renderDataTable({
  req(my_grouped_dataset())
  show_data_table(my_grouped_dataset())
})
```

```{r download_grouped, context="server"}
output$download_grouped <- create_download_handler(my_grouped_dataset(), "grouped_dataset")

observeEvent(input$copy_grouped, {
  clipr::write_clip(my_grouped_dataset(), allow_non_interactive=TRUE)
})
```

```{r column_processing, context="server"}
observe({
  req(dataset())
  duplicate_warning("column_grouping_var", "column_data_values")

  if(input$column_grouping_var != input$column_data_values) {
    shinyFeedback::hideFeedback("column_grouping_var")
    shinyFeedback::hideFeedback("column_data_values")
  }
})

my_column_dataset <- reactive({
  req(dataset())
  req(input$column_grouping_var != input$column_data_values)
  
  create_column_output(dataset(), input$column_grouping_var, input$column_data_values)
})
```

```{r column_ui, context="server"}
output$column_output <- renderUI({
  create_table_UI("column_table", isTruthy(dataset()))
  #browser()
  # tabsetPanel(
  #   tabPanel("Data", create_table_UI("column_table", isTruthy(dataset()))),
  #   tabPanel("Example")
  # )
})

output$column_table <- DT::renderDataTable({
  req(my_column_dataset())
  show_data_table(my_column_dataset())
})
```

```{r download_column, context="server"}
output$download_column <- create_download_handler(my_column_dataset(), "column_dataset")

observeEvent(input$copy_column, {
  clipr::write_clip(my_column_dataset(), allow_non_interactive=TRUE)
})
```

```{r transpose_ui, context="server"}
output$transposed_output <- renderUI({
  create_table_UI("transposed_table", isTruthy(dataset()))#, msg = "This format will only download as a file if the dataset has (unique) row and column names.")
})

output$transposed_table <- DT::renderDataTable({
  req(my_transposed_dataset())
  show_data_table(my_transposed_dataset())
})
```

```{r transpose_processing, context="server"}
my_transposed_dataset <- reactive({
  req(dataset())
  if(anyDuplicated(dataset()[[1]]) == 0){ # no duplicate row names so we can do it properly
    ds <- tibble::column_to_rownames(dataset(), colnames(dataset())[1])
    tibble::as_tibble(t(ds), rownames="row_names")
  } else {
    t(dataset()) # we can transpose it but it won't download properly
  }
})
```

```{r download_transposed, context="server"}
output$download_transposed <- create_download_handler(my_transposed_dataset(), "transposed_dataset")

observeEvent(input$copy_transposed, {
  clipr::write_clip(my_transposed_dataset(), allow_non_interactive=TRUE)
})
```

```{r contingency_processing, context="server"}
observe({
  req(dataset())
  duplicate_warning("contingency_varA", "contingency_varB")

  if(input$contingency_varA != input$contingency_varB) {
    shinyFeedback::hideFeedback("contingency_varA")
    shinyFeedback::hideFeedback("contingency_varB")
  }
})

# check if there's a unique identifier
my_contingency_table <- reactive({
  req(dataset())
  req(input$contingency_varA != input$contingency_varB)
  my_dataset <- dataset()
  
  my_dataset %>%
    dplyr::count(.data[[input$contingency_varA]], .data[[input$contingency_varB]]) %>%
    tidyr::spread(key = .data[[input$contingency_varB]], value = n)
})
```

```{r contingency_ui, context="server"}
output$contingency_output <- renderUI({
  create_table_UI("contingency_table", isTruthy(dataset()))
})

output$contingency_table <- DT::renderDataTable({
  req(my_contingency_table())
  show_data_table(my_contingency_table())
})
```

```{r download_contingency, context="server"}
output$download_contingency <- create_download_handler(my_contingency_table(), "contingency_table")

observeEvent(input$copy_contingency, {
  clipr::write_clip(my_contingency_table(), allow_non_interactive=TRUE)
})
```

<!--[Place your content here]{.navbar-fixed-bottom .text-muted .bg-info} -->
